############## data ############## From : https://docs.google.com/presentation/d/1H_WuzeAGkW3xZvo3oN4qGZWfw2eBuUzMhPLeShYAQoU/edit?slide=id.g36971dee1d1_0_0#slide=id.g36971dee1d1_0_0
EGamma0_Run2025B_v1:
  nanoAOD:
    PromptReco: /EGamma0/Run2025B-PromptReco-v1/NANOAOD
EGamma0_Run2025C_v1:
  nanoAOD:
    PromptReco: /EGamma0/Run2025C-PromptReco-v1/NANOAOD
EGamma0_Run2025C_v2:
  nanoAOD:
    PromptReco: /EGamma0/Run2025C-PromptReco-v2/NANOAOD
EGamma0_Run2025D_v1:
  nanoAOD:
    PromptReco: /EGamma0/Run2025D-PromptReco-v1/NANOAOD
EGamma0_Run2025E_v1:
  nanoAOD:
    PromptReco: /EGamma0/Run2025E-PromptReco-v1/NANOAOD
EGamma0_Run2025F_v1:
  nanoAOD:
    PromptReco: /EGamma0/Run2025F-PromptReco-v1/NANOAOD
EGamma0_Run2025F_v2:
  nanoAOD:
    PromptReco: /EGamma0/Run2025F-PromptReco-v2/NANOAOD
EGamma0_Run2025G_v1:
  nanoAOD:
    PromptReco: /EGamma0/Run2025G-PromptReco-v1/NANOAOD
EGamma1_Run2025B_v1:
  nanoAOD:
    PromptReco: /EGamma1/Run2025B-PromptReco-v1/NANOAOD
EGamma1_Run2025C_v1:
  nanoAOD:
    PromptReco: /EGamma1/Run2025C-PromptReco-v1/NANOAOD
EGamma1_Run2025C_v2:
  nanoAOD:
    PromptReco: /EGamma1/Run2025C-PromptReco-v2/NANOAOD
EGamma1_Run2025D_v1:
  nanoAOD:
    PromptReco: /EGamma1/Run2025D-PromptReco-v1/NANOAOD
EGamma1_Run2025E_v1:
  nanoAOD:
    PromptReco: /EGamma1/Run2025E-PromptReco-v1/NANOAOD
EGamma1_Run2025F_v1:
  nanoAOD:
    PromptReco: /EGamma1/Run2025F-PromptReco-v1/NANOAOD
EGamma1_Run2025F_v2:
  nanoAOD:
    PromptReco: /EGamma1/Run2025F-PromptReco-v2/NANOAOD
EGamma1_Run2025G_v1:
  nanoAOD:
    PromptReco: /EGamma1/Run2025G-PromptReco-v1/NANOAOD
EGamma2_Run2025B_v1:
  nanoAOD:
    PromptReco: /EGamma2/Run2025B-PromptReco-v1/NANOAOD
EGamma2_Run2025C_v1:
  nanoAOD:
    PromptReco: /EGamma2/Run2025C-PromptReco-v1/NANOAOD
EGamma2_Run2025C_v2:
  nanoAOD:
    PromptReco: /EGamma2/Run2025C-PromptReco-v2/NANOAOD
EGamma2_Run2025D_v1:
  nanoAOD:
    PromptReco: /EGamma2/Run2025D-PromptReco-v1/NANOAOD
EGamma2_Run2025E_v1:
  nanoAOD:
    PromptReco: /EGamma2/Run2025E-PromptReco-v1/NANOAOD
EGamma2_Run2025F_v1:
  nanoAOD:
    PromptReco: /EGamma2/Run2025F-PromptReco-v1/NANOAOD
EGamma2_Run2025F_v2:
  nanoAOD:
    PromptReco: /EGamma2/Run2025F-PromptReco-v2/NANOAOD
EGamma2_Run2025G_v1:
  nanoAOD:
    PromptReco: /EGamma2/Run2025G-PromptReco-v1/NANOAOD
EGamma3_Run2025B_v1:
  nanoAOD:
    PromptReco: /EGamma3/Run2025B-PromptReco-v1/NANOAOD
EGamma3_Run2025C_v1:
  nanoAOD:
    PromptReco: /EGamma3/Run2025C-PromptReco-v1/NANOAOD
EGamma3_Run2025C_v2:
  nanoAOD:
    PromptReco: /EGamma3/Run2025C-PromptReco-v2/NANOAOD
EGamma3_Run2025D_v1:
  nanoAOD:
    PromptReco: /EGamma3/Run2025D-PromptReco-v1/NANOAOD
EGamma3_Run2025E_v1:
  nanoAOD:
    PromptReco: /EGamma3/Run2025E-PromptReco-v1/NANOAOD
EGamma3_Run2025F_v1:
  nanoAOD:
    PromptReco: /EGamma3/Run2025F-PromptReco-v1/NANOAOD
EGamma3_Run2025F_v2:
  nanoAOD:
    PromptReco: /EGamma3/Run2025F-PromptReco-v2/NANOAOD
EGamma3_Run2025G_v1:
  nanoAOD:
    PromptReco: /EGamma3/Run2025G-PromptReco-v1/NANOAOD
JetMET0_Run2025B_v1:
  nanoAOD:
    PromptReco: /JetMET0/Run2025B-PromptReco-v1/NANOAOD
JetMET0_Run2025C_v1:
  nanoAOD:
    PromptReco: /JetMET0/Run2025C-PromptReco-v1/NANOAOD
JetMET0_Run2025C_v2:
  nanoAOD:
    PromptReco: /JetMET0/Run2025C-PromptReco-v2/NANOAOD
JetMET0_Run2025D_v1:
  nanoAOD:
    PromptReco: /JetMET0/Run2025D-PromptReco-v1/NANOAOD
JetMET0_Run2025E_v1:
  nanoAOD:
    PromptReco: /JetMET0/Run2025E-PromptReco-v1/NANOAOD
JetMET0_Run2025F_v1:
  nanoAOD:
    PromptReco: /JetMET0/Run2025F-PromptReco-v1/NANOAOD
JetMET0_Run2025F_v2:
  nanoAOD:
    PromptReco: /JetMET0/Run2025F-PromptReco-v2/NANOAOD
JetMET0_Run2025G_v1:
  nanoAOD:
    PromptReco: /JetMET0/Run2025G-PromptReco-v1/NANOAOD
JetMET1_Run2025B_v1:
  nanoAOD:
    PromptReco: /JetMET1/Run2025B-PromptReco-v1/NANOAOD
JetMET1_Run2025C_v1:
  nanoAOD:
    PromptReco: /JetMET1/Run2025C-PromptReco-v1/NANOAOD
JetMET1_Run2025C_v2:
  nanoAOD:
    PromptReco: /JetMET1/Run2025C-PromptReco-v2/NANOAOD
JetMET1_Run2025D_v1:
  nanoAOD:
    PromptReco: /JetMET1/Run2025D-PromptReco-v1/NANOAOD
JetMET1_Run2025E_v1:
  nanoAOD:
    PromptReco: /JetMET1/Run2025E-PromptReco-v1/NANOAOD
JetMET1_Run2025F_v1:
  nanoAOD:
    PromptReco: /JetMET1/Run2025F-PromptReco-v1/NANOAOD
JetMET1_Run2025F_v2:
  nanoAOD:
    PromptReco: /JetMET1/Run2025F-PromptReco-v2/NANOAOD
JetMET1_Run2025G_v1:
  nanoAOD:
    PromptReco: /JetMET1/Run2025G-PromptReco-v1/NANOAOD
Muon0_Run2025B_v1:
  nanoAOD:
    PromptReco: /Muon0/Run2025B-PromptReco-v1/NANOAOD
Muon0_Run2025C_v1:
  nanoAOD:
    PromptReco: /Muon0/Run2025C-PromptReco-v1/NANOAOD
Muon0_Run2025C_v2:
  nanoAOD:
    PromptReco: /Muon0/Run2025C-PromptReco-v2/NANOAOD
Muon0_Run2025D_v1:
  nanoAOD:
    PromptReco: /Muon0/Run2025D-PromptReco-v1/NANOAOD
Muon0_Run2025E_v1:
  nanoAOD:
    PromptReco: /Muon0/Run2025E-PromptReco-v1/NANOAOD
Muon0_Run2025F_v1:
  nanoAOD:
    PromptReco: /Muon0/Run2025F-PromptReco-v1/NANOAOD
Muon0_Run2025F_v2:
  nanoAOD:
    PromptReco: /Muon0/Run2025F-PromptReco-v2/NANOAOD
Muon0_Run2025G_v1:
  nanoAOD:
    PromptReco: /Muon0/Run2025G-PromptReco-v1/NANOAOD
Muon1_Run2025B_v1:
  nanoAOD:
    PromptReco: /Muon1/Run2025B-PromptReco-v1/NANOAOD
Muon1_Run2025C_v1:
  nanoAOD:
    PromptReco: /Muon1/Run2025C-PromptReco-v1/NANOAOD
Muon1_Run2025C_v2:
  nanoAOD:
    PromptReco: /Muon1/Run2025C-PromptReco-v2/NANOAOD
Muon1_Run2025D_v1:
  nanoAOD:
    PromptReco: /Muon1/Run2025D-PromptReco-v1/NANOAOD
Muon1_Run2025E_v1:
  nanoAOD:
    PromptReco: /Muon1/Run2025E-PromptReco-v1/NANOAOD
Muon1_Run2025F_v1:
  nanoAOD:
    PromptReco: /Muon1/Run2025F-PromptReco-v1/NANOAOD
Muon1_Run2025F_v2:
  nanoAOD:
    PromptReco: /Muon1/Run2025F-PromptReco-v2/NANOAOD
Muon1_Run2025G_v1:
  nanoAOD:
    PromptReco: /Muon1/Run2025G-PromptReco-v1/NANOAOD
MuonEG_Run2025B_v1:
  nanoAOD:
    PromptReco: /MuonEG/Run2025B-PromptReco-v1/NANOAOD
MuonEG_Run2025C_v1:
  nanoAOD:
    PromptReco: /MuonEG/Run2025C-PromptReco-v1/NANOAOD
MuonEG_Run2025C_v2:
  nanoAOD:
    PromptReco: /MuonEG/Run2025C-PromptReco-v2/NANOAOD
MuonEG_Run2025D_v1:
  nanoAOD:
    PromptReco: /MuonEG/Run2025D-PromptReco-v1/NANOAOD
MuonEG_Run2025E_v1:
  nanoAOD:
    PromptReco: /MuonEG/Run2025E-PromptReco-v1/NANOAOD
MuonEG_Run2025F_v1:
  nanoAOD:
    PromptReco: /MuonEG/Run2025F-PromptReco-v1/NANOAOD
MuonEG_Run2025F_v2:
  nanoAOD:
    PromptReco: /MuonEG/Run2025F-PromptReco-v2/NANOAOD
MuonEG_Run2025G_v1:
  nanoAOD:
    PromptReco: /MuonEG/Run2025G-PromptReco-v1/NANOAOD
ParkingHH0_Run2025B_v1:
  nanoAOD:
    PromptReco: /ParkingHH0/Run2025B-PromptReco-v1/NANOAOD
ParkingHH0_Run2025C_v1:
  nanoAOD:
    PromptReco: /ParkingHH0/Run2025C-PromptReco-v1/NANOAOD
ParkingHH0_Run2025C_v2:
  nanoAOD:
    PromptReco: /ParkingHH0/Run2025C-PromptReco-v2/NANOAOD
ParkingHH0_Run2025D_v1:
  nanoAOD:
    PromptReco: /ParkingHH0/Run2025D-PromptReco-v1/NANOAOD
ParkingHH0_Run2025E_v1:
  nanoAOD:
    PromptReco: /ParkingHH0/Run2025E-PromptReco-v1/NANOAOD
ParkingHH0_Run2025F_v1:
  nanoAOD:
    PromptReco: /ParkingHH0/Run2025F-PromptReco-v1/NANOAOD
ParkingHH0_Run2025F_v2:
  nanoAOD:
    PromptReco: /ParkingHH0/Run2025F-PromptReco-v2/NANOAOD
ParkingHH0_Run2025G_v1:
  nanoAOD:
    PromptReco: /ParkingHH0/Run2025G-PromptReco-v1/NANOAOD
ParkingHH1_Run2025B_v1:
  nanoAOD:
    PromptReco: /ParkingHH1/Run2025B-PromptReco-v1/NANOAOD
ParkingHH1_Run2025C_v1:
  nanoAOD:
    PromptReco: /ParkingHH1/Run2025C-PromptReco-v1/NANOAOD
ParkingHH1_Run2025C_v2:
  nanoAOD:
    PromptReco: /ParkingHH1/Run2025C-PromptReco-v2/NANOAOD
ParkingHH1_Run2025D_v1:
  nanoAOD:
    PromptReco: /ParkingHH1/Run2025D-PromptReco-v1/NANOAOD
ParkingHH1_Run2025E_v1:
  nanoAOD:
    PromptReco: /ParkingHH1/Run2025E-PromptReco-v1/NANOAOD
ParkingHH1_Run2025F_v1:
  nanoAOD:
    PromptReco: /ParkingHH1/Run2025F-PromptReco-v1/NANOAOD
ParkingHH1_Run2025F_v2:
  nanoAOD:
    PromptReco: /ParkingHH1/Run2025F-PromptReco-v2/NANOAOD
ParkingHH1_Run2025G_v1:
  nanoAOD:
    PromptReco: /ParkingHH1/Run2025G-PromptReco-v1/NANOAOD
ParkingVBF0_Run2025B_v1:
  nanoAOD:
    PromptReco: /ParkingVBF0/Run2025B-PromptReco-v1/NANOAOD
ParkingVBF0_Run2025C_v1:
  nanoAOD:
    PromptReco: /ParkingVBF0/Run2025C-PromptReco-v1/NANOAOD
ParkingVBF0_Run2025C_v2:
  nanoAOD:
    PromptReco: /ParkingVBF0/Run2025C-PromptReco-v2/NANOAOD
ParkingVBF0_Run2025D_v1:
  nanoAOD:
    PromptReco: /ParkingVBF0/Run2025D-PromptReco-v1/NANOAOD
ParkingVBF0_Run2025E_v1:
  nanoAOD:
    PromptReco: /ParkingVBF0/Run2025E-PromptReco-v1/NANOAOD
ParkingVBF0_Run2025F_v1:
  nanoAOD:
    PromptReco: /ParkingVBF0/Run2025F-PromptReco-v1/NANOAOD
ParkingVBF0_Run2025F_v2:
  nanoAOD:
    PromptReco: /ParkingVBF0/Run2025F-PromptReco-v2/NANOAOD
ParkingVBF0_Run2025G_v1:
  nanoAOD:
    PromptReco: /ParkingVBF0/Run2025G-PromptReco-v1/NANOAOD
ParkingVBF1_Run2025B_v1:
  nanoAOD:
    PromptReco: /ParkingVBF1/Run2025B-PromptReco-v1/NANOAOD
ParkingVBF1_Run2025C_v1:
  nanoAOD:
    PromptReco: /ParkingVBF1/Run2025C-PromptReco-v1/NANOAOD
ParkingVBF1_Run2025C_v2:
  nanoAOD:
    PromptReco: /ParkingVBF1/Run2025C-PromptReco-v2/NANOAOD
ParkingVBF1_Run2025D_v1:
  nanoAOD:
    PromptReco: /ParkingVBF1/Run2025D-PromptReco-v1/NANOAOD
ParkingVBF1_Run2025E_v1:
  nanoAOD:
    PromptReco: /ParkingVBF1/Run2025E-PromptReco-v1/NANOAOD
ParkingVBF1_Run2025F_v1:
  nanoAOD:
    PromptReco: /ParkingVBF1/Run2025F-PromptReco-v1/NANOAOD
ParkingVBF1_Run2025F_v2:
  nanoAOD:
    PromptReco: /ParkingVBF1/Run2025F-PromptReco-v2/NANOAOD
ParkingVBF1_Run2025G_v1:
  nanoAOD:
    PromptReco: /ParkingVBF1/Run2025G-PromptReco-v1/NANOAOD
ParkingVBF2_Run2025B_v1:
  nanoAOD:
    PromptReco: /ParkingVBF2/Run2025B-PromptReco-v1/NANOAOD
ParkingVBF2_Run2025C_v1:
  nanoAOD:
    PromptReco: /ParkingVBF2/Run2025C-PromptReco-v1/NANOAOD
ParkingVBF2_Run2025C_v2:
  nanoAOD:
    PromptReco: /ParkingVBF2/Run2025C-PromptReco-v2/NANOAOD
ParkingVBF2_Run2025D_v1:
  nanoAOD:
    PromptReco: /ParkingVBF2/Run2025D-PromptReco-v1/NANOAOD
ParkingVBF2_Run2025E_v1:
  nanoAOD:
    PromptReco: /ParkingVBF2/Run2025E-PromptReco-v1/NANOAOD
ParkingVBF2_Run2025F_v1:
  nanoAOD:
    PromptReco: /ParkingVBF2/Run2025F-PromptReco-v1/NANOAOD
ParkingVBF2_Run2025F_v2:
  nanoAOD:
    PromptReco: /ParkingVBF2/Run2025F-PromptReco-v2/NANOAOD
ParkingVBF2_Run2025G_v1:
  nanoAOD:
    PromptReco: /ParkingVBF2/Run2025G-PromptReco-v1/NANOAOD
ParkingVBF3_Run2025B_v1:
  nanoAOD:
    PromptReco: /ParkingVBF3/Run2025B-PromptReco-v1/NANOAOD
ParkingVBF3_Run2025C_v1:
  nanoAOD:
    PromptReco: /ParkingVBF3/Run2025C-PromptReco-v1/NANOAOD
ParkingVBF3_Run2025C_v2:
  nanoAOD:
    PromptReco: /ParkingVBF3/Run2025C-PromptReco-v2/NANOAOD
ParkingVBF3_Run2025D_v1:
  nanoAOD:
    PromptReco: /ParkingVBF3/Run2025D-PromptReco-v1/NANOAOD
ParkingVBF3_Run2025E_v1:
  nanoAOD:
    PromptReco: /ParkingVBF3/Run2025E-PromptReco-v1/NANOAOD
ParkingVBF3_Run2025F_v1:
  nanoAOD:
    PromptReco: /ParkingVBF3/Run2025F-PromptReco-v1/NANOAOD
ParkingVBF3_Run2025F_v2:
  nanoAOD:
    PromptReco: /ParkingVBF3/Run2025F-PromptReco-v2/NANOAOD
ParkingVBF3_Run2025G_v1:
  nanoAOD:
    PromptReco: /ParkingVBF3/Run2025G-PromptReco-v1/NANOAOD
ParkingVBF4_Run2025B_v1:
  nanoAOD:
    PromptReco: /ParkingVBF4/Run2025B-PromptReco-v1/NANOAOD
ParkingVBF4_Run2025C_v1:
  nanoAOD:
    PromptReco: /ParkingVBF4/Run2025C-PromptReco-v1/NANOAOD
ParkingVBF4_Run2025C_v2:
  nanoAOD:
    PromptReco: /ParkingVBF4/Run2025C-PromptReco-v2/NANOAOD
ParkingVBF4_Run2025D_v1:
  nanoAOD:
    PromptReco: /ParkingVBF4/Run2025D-PromptReco-v1/NANOAOD
ParkingVBF4_Run2025E_v1:
  nanoAOD:
    PromptReco: /ParkingVBF4/Run2025E-PromptReco-v1/NANOAOD
ParkingVBF4_Run2025F_v1:
  nanoAOD:
    PromptReco: /ParkingVBF4/Run2025F-PromptReco-v1/NANOAOD
ParkingVBF4_Run2025F_v2:
  nanoAOD:
    PromptReco: /ParkingVBF4/Run2025F-PromptReco-v2/NANOAOD
ParkingVBF4_Run2025G_v1:
  nanoAOD:
    PromptReco: /ParkingVBF4/Run2025G-PromptReco-v1/NANOAOD
ParkingVBF5_Run2025B_v1:
  nanoAOD:
    PromptReco: /ParkingVBF5/Run2025B-PromptReco-v1/NANOAOD
ParkingVBF5_Run2025C_v1:
  nanoAOD:
    PromptReco: /ParkingVBF5/Run2025C-PromptReco-v1/NANOAOD
ParkingVBF5_Run2025C_v2:
  nanoAOD:
    PromptReco: /ParkingVBF5/Run2025C-PromptReco-v2/NANOAOD
ParkingVBF5_Run2025D_v1:
  nanoAOD:
    PromptReco: /ParkingVBF5/Run2025D-PromptReco-v1/NANOAOD
ParkingVBF5_Run2025E_v1:
  nanoAOD:
    PromptReco: /ParkingVBF5/Run2025E-PromptReco-v1/NANOAOD
ParkingVBF5_Run2025F_v1:
  nanoAOD:
    PromptReco: /ParkingVBF5/Run2025F-PromptReco-v1/NANOAOD
ParkingVBF5_Run2025F_v2:
  nanoAOD:
    PromptReco: /ParkingVBF5/Run2025F-PromptReco-v2/NANOAOD
ParkingVBF5_Run2025G_v1:
  nanoAOD:
    PromptReco: /ParkingVBF5/Run2025G-PromptReco-v1/NANOAOD
ParkingVBF6_Run2025B_v1:
  nanoAOD:
    PromptReco: /ParkingVBF6/Run2025B-PromptReco-v1/NANOAOD
ParkingVBF6_Run2025C_v1:
  nanoAOD:
    PromptReco: /ParkingVBF6/Run2025C-PromptReco-v1/NANOAOD
ParkingVBF6_Run2025C_v2:
  nanoAOD:
    PromptReco: /ParkingVBF6/Run2025C-PromptReco-v2/NANOAOD
ParkingVBF6_Run2025D_v1:
  nanoAOD:
    PromptReco: /ParkingVBF6/Run2025D-PromptReco-v1/NANOAOD
ParkingVBF6_Run2025E_v1:
  nanoAOD:
    PromptReco: /ParkingVBF6/Run2025E-PromptReco-v1/NANOAOD
ParkingVBF6_Run2025F_v1:
  nanoAOD:
    PromptReco: /ParkingVBF6/Run2025F-PromptReco-v1/NANOAOD
ParkingVBF6_Run2025F_v2:
  nanoAOD:
    PromptReco: /ParkingVBF6/Run2025F-PromptReco-v2/NANOAOD
ParkingVBF6_Run2025G_v1:
  nanoAOD:
    PromptReco: /ParkingVBF6/Run2025G-PromptReco-v1/NANOAOD
ParkingVBF7_Run2025B_v1:
  nanoAOD:
    PromptReco: /ParkingVBF7/Run2025B-PromptReco-v1/NANOAOD
ParkingVBF7_Run2025C_v1:
  nanoAOD:
    PromptReco: /ParkingVBF7/Run2025C-PromptReco-v1/NANOAOD
ParkingVBF7_Run2025C_v2:
  nanoAOD:
    PromptReco: /ParkingVBF7/Run2025C-PromptReco-v2/NANOAOD
ParkingVBF7_Run2025D_v1:
  nanoAOD:
    PromptReco: /ParkingVBF7/Run2025D-PromptReco-v1/NANOAOD
ParkingVBF7_Run2025E_v1:
  nanoAOD:
    PromptReco: /ParkingVBF7/Run2025E-PromptReco-v1/NANOAOD
ParkingVBF7_Run2025F_v1:
  nanoAOD:
    PromptReco: /ParkingVBF7/Run2025F-PromptReco-v1/NANOAOD
ParkingVBF7_Run2025F_v2:
  nanoAOD:
    PromptReco: /ParkingVBF7/Run2025F-PromptReco-v2/NANOAOD
ParkingVBF7_Run2025G_v1:
  nanoAOD:
    PromptReco: /ParkingVBF7/Run2025G-PromptReco-v1/NANOAOD
Tau_Run2025B_v1:
  nanoAOD:
    PromptReco: /Tau/Run2025B-PromptReco-v1/NANOAOD
Tau_Run2025C_v1:
  nanoAOD:
    PromptReco: /Tau/Run2025C-PromptReco-v1/NANOAOD
Tau_Run2025C_v2:
  nanoAOD:
    PromptReco: /Tau/Run2025C-PromptReco-v2/NANOAOD
Tau_Run2025D_v1:
  nanoAOD:
    PromptReco: /Tau/Run2025D-PromptReco-v1/NANOAOD
Tau_Run2025E_v1:
  nanoAOD:
    PromptReco: /Tau/Run2025E-PromptReco-v1/NANOAOD
Tau_Run2025F_v1:
  nanoAOD:
    PromptReco: /Tau/Run2025F-PromptReco-v1/NANOAOD
Tau_Run2025F_v2:
  nanoAOD:
    PromptReco: /Tau/Run2025F-PromptReco-v2/NANOAOD
Tau_Run2025G_v1:
  nanoAOD:
    PromptReco: /Tau/Run2025G-PromptReco-v1/NANOAOD

# MC Samples: https://cms-pdmv-prod.web.cern.ch/grasp/samples?campaign=Run3Winter25*GS 
############## amcatnloFXFX ##############
############## DYto2L ##############
DYto2E_M_50_amcatnloFXFX:
  crossSection: DY_NNLO_QCD+NLO_EW
  generator: amcatnlo
  miniAOD:
  nanoAOD:
    Winter25: /DYTo2L-2Jets_Par-MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Winter25NanoAOD-142X_mcRun3_2025_realistic_v7-v2/NANOAODSIM
DYto2Mu_M_50_amcatnloFXFX:
  crossSection: DY_NNLO_QCD+NLO_EW
  generator: amcatnlo
  miniAOD:
  nanoAOD:
    Winter25: /DYTo2L-2Jets_Par-MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Winter25NanoAOD-142X_mcRun3_2025_realistic_v7-v2/NANOAODSIM
DYto2Tau_M_50_amcatnloFXFX:
  crossSection: DY_NNLO_QCD+NLO_EW
  generator: amcatnlo
  miniAOD:
  nanoAOD:
    Winter25: /DYTo2L-2Jets_Par-MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Winter25NanoAOD-142X_mcRun3_2025_realistic_v7-v2/NANOAODSIM
########## Jet Binned #######

DYto2E_M_50_1J_MadgraphMLM:
  crossSection: DYto2L_M_50_1J_amcatnloFXFX # should be changed..
  generator: Madgraph
  miniAOD:
  nanoAOD:
    Winter25: /DYTo2L-4Jets_Par-1J-MLL-50_TuneCP5_13p6TeV_madgraphMLM-pythia8/Run3Winter25NanoAOD-142X_mcRun3_2025_realistic_v7-v2/NANOAODSIM