############## DY ##############
Muon0_Run2024C_v1: { }
Muon0_Run2024D_v1: { }
Muon0_Run2024E_v1: { }
Muon0_Run2024F_v1: { }
Muon0_Run2024G_v1: { }
Muon0_Run2024H_v1: { }
Muon0_Run2024I_v1: { }
Muon0_Run2024I_v2: { }
Muon1_Run2024C_v1: { }
Muon1_Run2024D_v1: { }
Muon1_Run2024E_v1: { }
Muon1_Run2024F_v1: { }
Muon1_Run2024G_v1: { }
Muon1_Run2024H_v1: { }
Muon1_Run2024I_v1: { }
Muon1_Run2024I_v2: { }

############## amcatnloFXFX ##############
############## DYto2L ##############
DYto2E_M_50_amcatnloFXFX:
  crossSection: DY_NNLO_QCD+NLO_EW
  generator: amcatnloFXFX
  miniAOD: /DYto2E-2Jets_Bin-MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v4/MINIAODSIM
DYto2Mu_M_50_amcatnloFXFX:
  crossSection: DY_NNLO_QCD+NLO_EW
  generator: amcatnloFXFX
  miniAOD: /DYto2Mu-2Jets_Bin-MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v6/MINIAODSIM
DYto2Tau_M_50_amcatnloFXFX:
  crossSection: DY_NNLO_QCD+NLO_EW
  generator: amcatnloFXFX
  miniAOD: /DYto2Tau-2Jets_Bin-MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v7/MINIAODSIM

############## GGH ##############
############## HtoMuMu ##############
GluGluHto2Mu:
  crossSection: GluGluHto2Mu
  generator: powheg
  miniAOD: /GluGluH-Hto2Mu_Par-M-125_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM

############## ST ##############
TbarBtoLminusNuB_s_channel_4FS:
  crossSection: TbarBtoLminusNuB_s_channel_4FS
  generator: amcatnlo
  miniAOD: /TbarBtoLminusNuB-s-channel-4FS_TuneCP5_13p6TeV_amcatnlo-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
TBbartoLplusNuBbar_s_channel_4FS:
  crossSection: TBbartoLplusNuBbar_s_channel_4FS
  generator: amcatnlo
  miniAOD: /TBbartoLplusNuBbar-s-channel-4FS_TuneCP5_13p6TeV_amcatnlo-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
TbarBQtoLNu_t_channel_4FS:
  crossSection: TbarBQtoLNu_t_channel_4FS
  generator: powheg
  miniAOD: /TbarBQtoLNu-t-channel-4FS_TuneCP5_13p6TeV_powheg-madspin-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
TbarBQto2Q_t_channel_4FS:
  crossSection: TbarBQto2Q_t_channel_4FS
  generator: powheg
  miniAOD: /TbarBQto2Q-t-channel-4FS_TuneCP5_13p6TeV_powheg-madspin-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
TBbarQtoLNu_t_channel_4FS:
  crossSection: TBbarQtoLNu_t_channel_4FS
  generator: powheg
  miniAOD: /TBbarQtoLNu-t-channel-4FS_TuneCP5_13p6TeV_powheg-madspin-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
TBbarQto2Q_t_channel_4FS:
  crossSection: TBbarQto2Q_t_channel_4FS
  generator: powheg
  miniAOD: /TBbarQto2Q-t-channel-4FS_TuneCP5_13p6TeV_powheg-madspin-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM

TbarWplusto2L2Nu:
  crossSection: TbarWplusto2L2Nu
  generator: powheg
  miniAOD: /TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
TbarWplusto4Q:
  crossSection: TbarWplusto4Q
  generator: powheg
  miniAOD: /TbarWplusto4Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
TbarWplustoLNu2Q:
  crossSection: TbarWplustoLNu2Q
  generator: powheg
  miniAOD: /TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
TWminusto2L2Nu:
  crossSection: TWminusto2L2Nu
  generator: powheg
  miniAOD: /TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
TWminusto4Q:
  crossSection: TWminusto4Q
  generator: powheg
  miniAOD: /TWminusto4Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
TWminustoLNu2Q:
  crossSection: TWminustoLNu2Q
  generator: powheg
  miniAOD: /TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM

############## TT ##############
TTH_Hto2Mu:
  crossSection: TTH_Hto2Mu
  generator: powheg
  miniAOD: /TTH-Hto2Mu_Par-M-125_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM

TTto2L2Nu:
  crossSection: TTto2L2Nu
  generator: powheg
  miniAOD: /TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/MINIAODSIM
TTto4Q:
  crossSection: TTto4Q
  generator: powheg
  miniAOD: /TTto4Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
TTtoLNu2Q:
  crossSection: TTtoLNu2Q
  generator: powheg
  miniAOD: /TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
VBFHto2Mu:
  crossSection: VBFHto2Mu
  generator: powheg
  miniAOD: /VBFH-Hto2Mu_Par-M-125_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
WminusH_Hto2Mu_WtoAll:
  crossSection: WminusH_Hto2Mu_WtoAll
  generator: powheg
  miniAOD: /WminusH-Hto2Mu_Par-M-125_TuneCP5_13p6TeV_powhegMINLO-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/MINIAODSIM
WplusH_Hto2Mu_WtoAll:
  crossSection: WplusH_Hto2Mu_WtoAll
  generator: powheg
  miniAOD: /WplusH-Hto2Mu_Par-M-125_TuneCP5_13p6TeV_powhegMINLO-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/MINIAODSIM
WtoENu_amcatnloFXFX:
  crossSection: WtoLNu_NNLO_QCD+NLO_EW_one_flav
  generator: amcatnloFXFX
  miniAOD: /WtoENu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/MINIAODSIM
WtoMuNu_amcatnloFXFX:
  crossSection: WtoLNu_NNLO_QCD+NLO_EW_one_flav
  generator: amcatnloFXFX
  miniAOD: /WtoMuNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/MINIAODSIM
WtoTauNu_amcatnloFXFX:
  crossSection: WtoLNu_NNLO_QCD+NLO_EW_one_flav
  generator: amcatnloFXFX
  miniAOD: /WtoTauNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/MINIAODSIM

############## VV ##############
WWto2L2Nu_powheg:
  crossSection: WWto2L2Nu
  generator: powheg
  miniAOD: /WWto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
WWto4Q_powheg:
  crossSection: WWto4Q
  generator: powheg
  miniAOD: /WWto4Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
WWtoLNu2Q_powheg:
  crossSection: WWtoLNu2Q
  generator: powheg
  miniAOD: /WWtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM

WZto2L2Q_powheg:
  crossSection: WZto2L2Q_powheg
  generator: powheg
  miniAOD: /WZto2L2Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
WZto3LNu_powheg:
  crossSection: WZto3LNu_powheg
  generator: powheg
  miniAOD: /WZto3LNu_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
WZtoLNu2Q_powheg:
  crossSection: WZtoLNu2Q_powheg
  generator: powheg
  miniAOD: /WZtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM

ZH_Hto2Mu_ZtoAll:
  crossSection: ZH_Hto2Mu_ZtoAll
  generator: powheg
  miniAOD: /ZH-Hto2Mu_Par-M-125_TuneCP5_13p6TeV_powhegMINLO-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/MINIAODSIM

ZZto2L2Nu_powheg:
  crossSection: ZZto2L2Nu_powheg
  generator: powheg
  miniAOD: /ZZto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
ZZto2L2Q_powheg:
  crossSection: ZZto2L2Q_powheg
  generator: powheg
  miniAOD: /ZZto2L2Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
ZZto2Nu2Q_powheg:
  crossSection: ZZto2Nu2Q_powheg
  generator: powheg
  miniAOD: /ZZto2Nu2Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
ZZto4L_powheg:
  crossSection: ZZto4L_powheg
  generator: powheg
  miniAOD: /ZZto4L_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM

EWK_2L2J_madgraph_herwig:
  crossSection: EWK_2L2J_madgraph_herwig
  generator: madgraph
  miniAOD: /EWK-2L2J_Bin-MLL-50-MJJ-120_TuneCH3_13p6TeV_madgraph-herwig7/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
