era: Run3_2022EE
luminosity: 26671.7  # pb-1
fs_nanoAOD:
  - 'T2_CH_CERN:/store/group/phys_higgs/HLepRare/skim_2025_v1/Run3_2022EE'
nano_version: v14
crossSectionsFile: FLAF/config/crossSections13p6TeV.yaml
use_stitching: false
met_type: PFMET
MET_flags:  # https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFiltersRun2#Run_3_2022_and_2023_data_and_MC
  - Flag_goodVertices
  - Flag_globalSuperTightHalo2016Filter
  - Flag_EcalDeadCellTriggerPrimitiveFilter
  - Flag_BadPFMuonFilter
  - Flag_BadPFMuonDzFilter
  - Flag_hfNoisyHitsFilter
  - Flag_eeBadScFilter
  - Flag_ecalBadCalibFilter
badMET_flag_runs:  # https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFiltersRun2#ECal_BadCalibration_Filter_Flag
  - 362433
  - 362760  # for 2022, Flag_ecalBadCalibFilter should not be used for a range of these two run numbers.
# lumiFile: /eos/user/c/cmsdqm/www/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
lumiFile: Corrections/data/golden_json/Cert_Collisions2022_355100_362760_Golden.json
