era: Run3_2023BPix
luminosity: 9693.0  # pb-1
fs_nanoAOD:
  - 'T2_CH_CERN:/store/group/phys_higgs/HLepRare/skim_2025_v1/Run3_2023BPix'
nano_version: v14
nanoAODVersions:
  data: 22Sep23
  mc: v12
crossSectionsFile: FLAF/config/crossSections13p6TeV.yaml
use_stitching: false
met_type: PFMET
MET_flags:  # https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFiltersRun2#Run_3_2022_and_2023_data_and_MC
  - Flag_goodVertices
  - Flag_globalSuperTightHalo2016Filter
  - Flag_EcalDeadCellTriggerPrimitiveFilter
  - Flag_BadPFMuonFilter
  - Flag_BadPFMuonDzFilter
  - Flag_hfNoisyHitsFilter
  - Flag_eeBadScFilter
  - Flag_ecalBadCalibFilter
# lumiFile: /eos/user/c/cmsdqm/www/CAF/certification/Collisions23/Cert_Collisions2023_366442_370790_Golden.json
lumiFile: Corrections/data/golden_json/Cert_Collisions2023_366442_370790_Golden.json
