stitched_binning:
  - name: bin1
    bin_selection: "LHE_Vpt >= 0 && LHE_Vpt < 40 && LHE_NpNLO == 0"
  - name: bin2
    bin_selection: "LHE_Vpt >= 0 && LHE_Vpt < 40 && LHE_NpNLO == 1"
  - name: bin3
    bin_selection: "LHE_Vpt >= 0 && LHE_Vpt < 40 && LHE_NpNLO == 2"
  - name: bin4
    bin_selection: "LHE_Vpt >= 0 && LHE_Vpt < 40 && LHE_NpNLO == 3"
  - name: bin5
    bin_selection: "LHE_Vpt >= 0 && LHE_Vpt < 40 && LHE_NpNLO >= 4"

  - name: bin6
    bin_selection: "LHE_Vpt >= 40 && LHE_Vpt < 100 && LHE_NpNLO == 0"
  - name: bin7
    bin_selection: "LHE_Vpt >= 40 && LHE_Vpt < 100 && LHE_NpNLO == 1"
  - name: bin8
    bin_selection: "LHE_Vpt >= 40 && LHE_Vpt < 100 && LHE_NpNLO == 2"
  - name: bin9
    bin_selection: "LHE_Vpt >= 40 && LHE_Vpt < 100 && LHE_NpNLO == 3"
  - name: bin10
    bin_selection: "LHE_Vpt >= 40 && LHE_Vpt < 100 && LHE_NpNLO >= 4"

  - name: bin11
    bin_selection: "LHE_Vpt >= 100 && LHE_Vpt < 200 && LHE_NpNLO == 0"
  - name: bin12
    bin_selection: "LHE_Vpt >= 100 && LHE_Vpt < 200 && LHE_NpNLO == 1"
  - name: bin13
    bin_selection: "LHE_Vpt >= 100 && LHE_Vpt < 200 && LHE_NpNLO == 2"
  - name: bin14
    bin_selection: "LHE_Vpt >= 100 && LHE_Vpt < 200 && LHE_NpNLO == 3"
  - name: bin15
    bin_selection: "LHE_Vpt >= 100 && LHE_Vpt < 200 && LHE_NpNLO >= 4"

  - name: bin16
    bin_selection: "LHE_Vpt >= 200 && LHE_Vpt < 400 && LHE_NpNLO == 0"
  - name: bin17
    bin_selection: "LHE_Vpt >= 200 && LHE_Vpt < 400 && LHE_NpNLO == 1"
  - name: bin18
    bin_selection: "LHE_Vpt >= 200 && LHE_Vpt < 400 && LHE_NpNLO == 2"
  - name: bin19
    bin_selection: "LHE_Vpt >= 200 && LHE_Vpt < 400 && LHE_NpNLO == 3"
  - name: bin20
    bin_selection: "LHE_Vpt >= 200 && LHE_Vpt < 400 && LHE_NpNLO >= 4"

  - name: bin21
    bin_selection: "LHE_Vpt >= 400 && LHE_Vpt < 600 && LHE_NpNLO == 0"
  - name: bin22
    bin_selection: "LHE_Vpt >= 400 && LHE_Vpt < 600 && LHE_NpNLO == 1"
  - name: bin23
    bin_selection: "LHE_Vpt >= 400 && LHE_Vpt < 600 && LHE_NpNLO == 2"
  - name: bin24
    bin_selection: "LHE_Vpt >= 400 && LHE_Vpt < 600 && LHE_NpNLO == 3"
  - name: bin25
    bin_selection: "LHE_Vpt >= 400 && LHE_Vpt < 600 && LHE_NpNLO >= 4"

  - name: bin26
    bin_selection: "LHE_Vpt >= 600 && LHE_Vpt < 10000 && LHE_NpNLO == 0"
  - name: bin27
    bin_selection: "LHE_Vpt >= 600 && LHE_Vpt < 10000 && LHE_NpNLO == 1"
  - name: bin28
    bin_selection: "LHE_Vpt >= 600 && LHE_Vpt < 10000 && LHE_NpNLO == 2"
  - name: bin29
    bin_selection: "LHE_Vpt >= 600 && LHE_Vpt < 10000 && LHE_NpNLO == 3"
  - name: bin30
    bin_selection: "LHE_Vpt >= 600 && LHE_Vpt < 10000 && LHE_NpNLO >= 4"
