name: Cross-section validation

on:
  pull_request:
    types: [ "opened", "synchronize", "reopened", "labeled" ]
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  cross-section-check:
    runs-on: ubuntu-latest
    steps:
      - uses: cms-flaf/FLAF/.github/actions/checkout-flaf@main

      - name: Get changed files
        id: changed_files
        uses: actions/github-script@v6
        with:
          script: |
            const files = await github.paginate(github.rest.pulls.listFiles, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            console.log(`Total files changed: ${files.length}`);
            const allChangedFiles = files.map(file => file.filename);
            const changedFiles = allChangedFiles.filter(file =>
              file.startsWith('config/crossSections') && file.endsWith('.yaml') ||
              file.startsWith('config/Run') && (file.endsWith('datasets.yaml') || file.endsWith('global.yaml'))
            );
            core.setOutput('files', btoa(changedFiles.join('\n')));
            const has_changes = changedFiles.length > 0 ? 'true' : 'false';
            console.log(`Has cross-section related changes: ${has_changes}`);
            core.setOutput('has_changes', has_changes);

      - name: Set up Python
        uses: actions/setup-python@v4
        if: ${{ steps.changed_files.outputs.has_changes == 'true' }}
        with:
          python-version: '3.x'

      - name: Install pyyaml
        if: ${{ steps.changed_files.outputs.has_changes == 'true' }}
        run: pip install pyyaml

      - name: Check cross-sections
        if: ${{ steps.changed_files.outputs.has_changes == 'true' }}
        run: python3 test/checkCrossSections.py Run3_2022 Run3_2022EE Run3_2023 Run3_2023BPix Run3_2024
